#!/usr/bin/env bash

ROOT="/home/murat/Media/8-Document/Knowledge"

result="$(
  rg \
    --line-number \
    --no-heading \
    --color=never \
    --no-ignore \
    --hidden \
    --max-depth 1 \
    --glob '!.git/**' \
    --glob '!.gitignore' \
    '.' "$ROOT" |
  fzf \
    --delimiter=: \
    --preview 'bat --color=always --style=numbers --highlight-line {2} --line-range :500 {1}' \
    --preview-window='right:60%'
)"

[[ -z "$result" ]] && exit 0

file="${result%%:*}"
rest="${result#*:}"
line="${rest%%:*}"

NVIM_APPNAME=astronvim nvim "+${line}" "$file"
